/* eslint-disable */

/**
 * Plio.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { createEndpoint, normalizePath } from '@1023-ventures/darri-core';


// Data Transfer Objects for individual endpoints

/**
 * no description
 */
export const VersionController = {

    /**
     */
    getVersion: createEndpoint<string, never, never, never>({
        method: 'GET',
        url: normalizePath('/plio/api/Version')
    }),
}
