/* tslint:disable */
/* eslint-disable */
/**
 * Burdi.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { exists } from '@1023-ventures/darri-core';


export type Message = {
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    tenantId?: string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    changedBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof Message
     */
    changedOn?: Date;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    createdBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof Message
     */
    createdOn?: Date;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    concurrency?: string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    topicId?: string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    userName?: string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    text?: string;
}

export const MessageModel = {
    id: 'id',
    tenantId: 'tenantId',
    changedBy: 'changedBy',
    changedOn: 'changedOn',
    createdBy: 'createdBy',
    createdOn: 'createdOn',
    concurrency: 'concurrency',
    topicId: 'topicId',
    userId: 'userId',
    userName: 'userName',
    text: 'text',
    _metadata: {
        id: { type: 'string' },
        tenantId: { type: 'string' },
        changedBy: { type: 'string' },
        changedOn: { type: 'Date' },
        createdBy: { type: 'string' },
        createdOn: { type: 'Date' },
        concurrency: { type: 'string' },
        topicId: { type: 'string' },
        userId: { type: 'string' },
        userName: { type: 'string' },
        text: { type: 'string' },
    }
}

export function MessageFromJSON(json: any): Message {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'tenantId': !exists(json, 'tenantId') ? undefined : json['tenantId'],
        'changedBy': !exists(json, 'changedBy') ? undefined : json['changedBy'],
        'changedOn': !exists(json, 'changedOn') ? undefined : new Date(json['changedOn']),
        'createdBy': !exists(json, 'createdBy') ? undefined : json['createdBy'],
        'createdOn': !exists(json, 'createdOn') ? undefined : new Date(json['createdOn']),
        'concurrency': !exists(json, 'concurrency') ? undefined : json['concurrency'],
        'topicId': !exists(json, 'topicId') ? undefined : json['topicId'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'userName': !exists(json, 'userName') ? undefined : json['userName'],
        'text': !exists(json, 'text') ? undefined : json['text'],
        
    };
}

export function MessageToJSON(value?: Message): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'tenantId': value.tenantId,
        'changedBy': value.changedBy,
        'changedOn': value.changedOn === undefined ? undefined : value.changedOn.toISOString(),
        'createdBy': value.createdBy,
        'createdOn': value.createdOn === undefined ? undefined : value.createdOn.toISOString(),
        'concurrency': value.concurrency,
        'topicId': value.topicId,
        'userId': value.userId,
        'userName': value.userName,
        'text': value.text,
        
    };
}


