/* tslint:disable */
/* eslint-disable */
/**
 * Plio.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { exists } from '@1023-ventures/darri-core';


export type Image = {
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    tenantId?: string;
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    changedBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof Image
     */
    changedOn?: Date;
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    createdBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof Image
     */
    createdOn?: Date;
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    concurrency?: string;
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    imageData?: string;
}

export const ImageModel = {
    id: 'id',
    tenantId: 'tenantId',
    changedBy: 'changedBy',
    changedOn: 'changedOn',
    createdBy: 'createdBy',
    createdOn: 'createdOn',
    concurrency: 'concurrency',
    name: 'name',
    userId: 'userId',
    imageData: 'imageData',
    _metadata: {
        id: { type: 'string' },
        tenantId: { type: 'string' },
        changedBy: { type: 'string' },
        changedOn: { type: 'Date' },
        createdBy: { type: 'string' },
        createdOn: { type: 'Date' },
        concurrency: { type: 'string' },
        name: { type: 'string' },
        userId: { type: 'string' },
        imageData: { type: 'string' },
    }
}

export function ImageFromJSON(json: any): Image {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'tenantId': !exists(json, 'tenantId') ? undefined : json['tenantId'],
        'changedBy': !exists(json, 'changedBy') ? undefined : json['changedBy'],
        'changedOn': !exists(json, 'changedOn') ? undefined : new Date(json['changedOn']),
        'createdBy': !exists(json, 'createdBy') ? undefined : json['createdBy'],
        'createdOn': !exists(json, 'createdOn') ? undefined : new Date(json['createdOn']),
        'concurrency': !exists(json, 'concurrency') ? undefined : json['concurrency'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'imageData': !exists(json, 'imageData') ? undefined : json['imageData'],
        
    };
}

export function ImageToJSON(value?: Image): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'tenantId': value.tenantId,
        'changedBy': value.changedBy,
        'changedOn': value.changedOn === undefined ? undefined : value.changedOn.toISOString(),
        'createdBy': value.createdBy,
        'createdOn': value.createdOn === undefined ? undefined : value.createdOn.toISOString(),
        'concurrency': value.concurrency,
        'name': value.name,
        'userId': value.userId,
        'imageData': value.imageData,
        
    };
}


