/* tslint:disable */
/* eslint-disable */
/**
 * Plio.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { exists } from '@1023-ventures/darri-core';


export type ImageData = {
    /**
     * 
     * @type {string}
     * @memberof ImageData
     */
    fileName?: string;
    /**
     * 
     * @type {string}
     * @memberof ImageData
     */
    image?: string;
}

export const ImageDataModel = {
    fileName: 'fileName',
    image: 'image',
    _metadata: {
        fileName: { type: 'string' },
        image: { type: 'string' },
    }
}

export function ImageDataFromJSON(json: any): ImageData {
    return {
        'fileName': !exists(json, 'fileName') ? undefined : json['fileName'],
        'image': !exists(json, 'image') ? undefined : json['image'],
        
    };
}

export function ImageDataToJSON(value?: ImageData): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'fileName': value.fileName,
        'image': value.image,
        
    };
}


