/* tslint:disable */
/* eslint-disable */
/**
 * Plio.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum SupportTicketStatus {
    Pending = 'Pending',
    Claimed = 'Claimed',
    Closed = 'Closed'
}

export function SupportTicketStatusFromJSON(json: any): SupportTicketStatus {
    return SupportTicketStatusFromJSONTyped(json, false);
}

export function SupportTicketStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupportTicketStatus {
    return json as SupportTicketStatus;
}

export function SupportTicketStatusToJSON(value?: SupportTicketStatus | null): any {
    return value as any;
}

